on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      # release:
      #   type: string
      #   required: true
      github-ref:
        type: string
        required: true

env:
  GITHUB_TAG_REF: ${{ inputs.github-ref }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "Called Environment ${{ inputs.environment }}"
      - run: echo "Called Version ${{ inputs.release }}"
      - name: Set tag
        run: echo "RELEASE_VERSION=${GITHUB_TAG_REF#refs/tag-name-v*/}" >> $GITHUB_ENV
      - run: echo "Release Version ${{ env.RELEASE_VERSION }}"
      - name: Set tag 2
        run: echo "RELEASE_VERSION2=${GITHUB_REF#refs/tag-name-v*/}" >> $GITHUB_ENV
      - run: echo "Release Version2 ${{ env.RELEASE_VERSION2 }}"

    


